name: example
description: A sample command-line application.
version: 1.0.0


environment:
  sdk: ^3.1.5

dependencies:
  firebase_verify_token_dart:
    path: ../

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
