name: firebase_verify_token_dart
description: Package to verify a firebase jwt token across multiple Firebase projects
version: 1.0.1
homepage: https://github.com/enzo-desimone/firebase_verify_token_dart

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  http: ^1.3.0
  jose_plus: ^0.4.6
  ntp: ^2.0.0

dev_dependencies:
  very_good_analysis: ^7.0.0

