name: firebase_verify_token_dart
description: Package to verify a firebase jwt token across multiple Firebase projects
version: 2.1.3
homepage: https://github.com/enzo-desimone/firebase_verify_token_dart

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  http: ^1.5.0
  intl: ^0.20.0
  jose_plus: ^0.4.7
  ntp_dart: ^1.1.1


dev_dependencies:
  very_good_analysis: ^9.0.0


